### ISSUE TITLE
Allergies dropdown hiding save button

### ISSUE THREAD

**Issue by vicaub** [vicaub/product-scanner#17]
I have the following issue on my Android phone (Samsung Galaxy S7)

When I go to my profil then my allergies, when I select click on the dropdown menu it hides the save button (check screenshot)
![screenshot_20190103-145045_productscanner](https://user-images.githubusercontent.com/25685231/50641070-1af7b400-0f67-11e9-86df-a034abce0fb8.jpg)

The only thing I can do is to press return and I won't save my allergies

**Comment by dlphn** [comment]
Yes, this is due to the fact that we have a very long list of allergens. The library I'm using for the multiple select provides a solution that restricts the size of the dropdown but I wasn't satisfied. The scrolling was really difficult and even if the 'Valider' button was visible, I couldn't click on it.

I will try to fix this soon.

**Comment by CecileSerene** [comment]
Also, the prompt to select allergies is in English
